#
#  TDS: 11/2011
#  PROTOTYPE - PROTOTYPE - PROTOTYPE
#  If you are surprised to see this here, just ignore it.
#  Many fields are probably inaccurate.
#
Catkin-ProjectName: ros_comm
Version: 0.0.1
Depends: catkin, genmsg, std_msgs, roscpp_core
         libapr1-dev, libaprutil1-dev, liblog4cxx10-dev, libboost-dev, libboost-all-dev
Description: ROS Communications
Author: Troy Straszheim <straszheim@willowgarage.com>, Ken Conley, Josh Faust et al
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org


Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
